import { DM_Sans } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "../../context/authContext";
import { LoadingProvider } from "../../context/loadContext";

const dm = DM_Sans({
  subsets: ["latin", "latin-ext"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
    "1000",
  ],
  variable: "--font-dm",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${dm.variable} font-sans`}>
        <LoadingProvider>
          <AuthContextProvider>{children}</AuthContextProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
